export const sidebarTopics = [
  {
    title: "🚀 JavaScript Fundamentals",
    category: "javascript",
    topics: [
      "Introduction to JavaScript",
      "Execution Context",
      "Global Execution Context",
      "Function Execution Context",
      "Call Stack",
      "Hoisting",
      "Temporal Dead Zone (TDZ)",
      "var vs let vs const",
      "Data Types",
      "Type Conversion",
      "Operators",
      "Truthy & Falsy Values",
    ],
  },
  {
    title: "📦 Scope & Functions",
    category: "javascript",
    topics: [
      "Scope",
      "Block Scope",
      "Function Scope",
      "Lexical Environment",
      "Scope Chain",
      "Closures",
      "Functions",
      "Arrow Functions",
      "Higher Order Functions",
      "Callback Functions",
      "IIFE",
    ],
  },
  {
    title: "🎯 Objects & OOP",
    category: "javascript",
    topics: [
      "Objects",
      "this Keyword",
      "call()",
      "apply()",
      "bind()",
      "Prototype",
      "Prototype Chain",
      "Object.create()",
      "Constructor Functions",
      "Classes",
      "Inheritance",
      "Encapsulation",
      "Polymorphism",
      "Abstraction",
    ],
  },
  {
    title: "⚡ Asynchronous JavaScript",
    category: "javascript",
    topics: [
      "Synchronous vs Asynchronous",
      "Web APIs",
      "Event Loop",
      "Callback Queue",
      "Microtask Queue",
      "Macrotask Queue",
      "Callbacks",
      "Callback Hell",
      "Promises",
      "Promise Chaining",
      "async/await",
      "fetch API",
    ],
  },
  {
    title: "🔥 Advanced JavaScript",
    category: "javascript",
    topics: [
      "Modules",
      "ES Modules",
      "CommonJS",
      "Iterators",
      "Generators",
      "Currying",
      "Memoization",
      "Debouncing",
      "Throttling",
      "Event Delegation",
      "Optional Chaining",
      "Nullish Coalescing",
      "Destructuring",
      "Spread Operator",
      "Rest Parameters",
    ],
  },
  {
    title: "🧠 Memory & Performance",
    category: "javascript",
    topics: [
      "Memory Management",
      "Garbage Collection",
      "Shallow Copy",
      "Deep Copy",
      "Pass by Value vs Reference",
      "Memory Leak",
      "Performance Optimization",
    ],
  },
  {
    title: "💻 Browser & DOM",
    category: "javascript",
    topics: [
      "DOM",
      "DOM Manipulation",
      "DOM Events",
      "Event Bubbling",
      "Event Capturing",
      "Event Delegation",
      "Local Storage",
      "Session Storage",
      "Cookies",
    ],
  },
  {
    title: "🎓 Interview Preparation",
    category: "javascript",
    topics: [
      "JavaScript Interview Questions",
      "Output Based Questions",
      "Tricky Programs",
      "Coding Challenges",
      "MCQs",
      "Cheat Sheets",
    ],
  },
]
